/**
 * TINY GENERATED CODE, DO NOT EDIT BY HAND
 * @project TinyHana.io
 */

entities.game.MainGroup.name = "MainGroup";
entities.game.MainGroup.load = function(world) {
    var arch0 = world.createArchetype(game.Camera, game.Limits, game.Speed, game.TeleportLimit, this.Component, ut.Core2D.Camera2D, ut.Core2D.TransformLocalPosition, ut.Core2D.TransformLocalRotation, ut.Core2D.TransformLocalScale, ut.Core2D.TransformNode, ut.EditorExtensions.CameraCullingMask, ut.layers.Default)
    var e0 = world.createEntity(arch0);
    world.setEntityName(e0, "Camera");
    var arch1 = world.createArchetype(this.Component, ut.Core2D.Sprite2DRenderer, ut.Core2D.TransformNode, ut.layers.Default)
    var e1 = world.createEntity(arch1);
    world.setEntityName(e1, "Background");
    var arch2 = world.createArchetype(this.Component, ut.Core2D.Sprite2DRenderer, ut.Core2D.TransformLocalPosition, ut.Core2D.TransformLocalRotation, ut.Core2D.TransformLocalScale, ut.Core2D.TransformNode, ut.layers.Default)
    var e2 = world.createEntity(arch2);
    world.setEntityName(e2, "bg1");
    var e3 = world.createEntity(arch2);
    world.setEntityName(e3, "bg2");
    var e4 = world.createEntity(arch2);
    world.setEntityName(e4, "bg5");
    var e5 = world.createEntity(arch2);
    world.setEntityName(e5, "bg4");
    var e6 = world.createEntity(arch2);
    world.setEntityName(e6, "bg3");
    var c0 = new ut.Core2D.TransformNode();
    world.setComponentData(e0, c0);
    var c1 = new ut.Core2D.TransformLocalPosition();
    var s0 = new ut.Math.Vector3();
    s0.x = -66.02;
    s0.y = 1.06;
    s0.z = -1;
    c1.position = s0;
    world.setComponentData(e0, c1);
    var c2 = new ut.Core2D.TransformLocalRotation();
    var s1 = new ut.Math.Quaternion();
    s1.x = 0;
    s1.y = 0;
    s1.z = 0;
    s1.w = 1;
    c2.rotation = s1;
    world.setComponentData(e0, c2);
    var c3 = new ut.Core2D.TransformLocalScale();
    var s2 = new ut.Math.Vector3();
    s2.x = 1;
    s2.y = 1;
    s2.z = 1;
    c3.scale = s2;
    world.setComponentData(e0, c3);
    var c4 = new ut.Core2D.Camera2D();
    c4.halfVerticalSize = 5;
    var s3 = new ut.Math.Rect();
    s3.x = 0;
    s3.y = 0;
    s3.width = 1;
    s3.height = 1;
    c4.rect = s3;
    var s4 = new ut.Core2D.Color();
    s4.r = 0;
    s4.g = 0;
    s4.b = 0;
    s4.a = 1;
    c4.backgroundColor = s4;
    c4.clearFlags = 1;
    c4.cullingMask = [ut.layers.Default.cid, ut.layers.TransparentFX.cid, ut.layers.IgnoreRaycast.cid, ut.layers.Water.cid, ut.layers.UI.cid, ut.layers.Grid.cid, ut.layers.Cutscene.cid];
    c4.cullingMode = 2;
    world.setComponentData(e0, c4);
    var c5 = new game.Limits();
    c5.minY = 0.3;
    c5.maxY = 3;
    world.setComponentData(e0, c5);
    var c6 = new game.TeleportLimit();
    c6.maxX = 58;
    c6.minX = -167;
    world.setComponentData(e0, c6);
    var c7 = new game.Speed();
    c7.speed = 10;
    world.setComponentData(e0, c7);
    var c8 = new ut.EditorExtensions.CameraCullingMask();
    c8.mask = -1;
    world.setComponentData(e0, c8);
    var c9 = new ut.Core2D.Sprite2DRenderer();
    c9.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/background');
    var s5 = new ut.Core2D.Color();
    s5.r = 1;
    s5.g = 1;
    s5.b = 1;
    s5.a = 1;
    c9.color = s5;
    c9.blending = 0;
    world.setComponentData(e1, c9);
    var c10 = new ut.Core2D.TransformNode();
    world.setComponentData(e1, c10);
    var c11 = new ut.Core2D.TransformNode();
    c11.parent = e1;
    world.setComponentData(e2, c11);
    var c12 = new ut.Core2D.TransformLocalPosition();
    var s6 = new ut.Math.Vector3();
    s6.x = -13.29092;
    s6.y = 1.661623;
    s6.z = 0;
    c12.position = s6;
    world.setComponentData(e2, c12);
    var c13 = new ut.Core2D.TransformLocalRotation();
    var s7 = new ut.Math.Quaternion();
    s7.x = 0;
    s7.y = 0;
    s7.z = 0;
    s7.w = 1;
    c13.rotation = s7;
    world.setComponentData(e2, c13);
    var c14 = new ut.Core2D.TransformLocalScale();
    var s8 = new ut.Math.Vector3();
    s8.x = 1;
    s8.y = 1;
    s8.z = 1;
    c14.scale = s8;
    world.setComponentData(e2, c14);
    var c15 = new ut.Core2D.Sprite2DRenderer();
    c15.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/bg1');
    var s9 = new ut.Core2D.Color();
    s9.r = 1;
    s9.g = 1;
    s9.b = 1;
    s9.a = 1;
    c15.color = s9;
    c15.blending = 0;
    world.setComponentData(e2, c15);
    var c16 = new ut.Core2D.TransformNode();
    c16.parent = e1;
    world.setComponentData(e3, c16);
    var c17 = new ut.Core2D.TransformLocalPosition();
    var s10 = new ut.Math.Vector3();
    s10.x = 37.01408;
    s10.y = 1.661625;
    s10.z = 0;
    c17.position = s10;
    world.setComponentData(e3, c17);
    var c18 = new ut.Core2D.TransformLocalRotation();
    var s11 = new ut.Math.Quaternion();
    s11.x = 0;
    s11.y = 0;
    s11.z = 0;
    s11.w = 1;
    c18.rotation = s11;
    world.setComponentData(e3, c18);
    var c19 = new ut.Core2D.TransformLocalScale();
    var s12 = new ut.Math.Vector3();
    s12.x = 1;
    s12.y = 1;
    s12.z = 1;
    c19.scale = s12;
    world.setComponentData(e3, c19);
    var c20 = new ut.Core2D.Sprite2DRenderer();
    c20.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/bg2');
    var s13 = new ut.Core2D.Color();
    s13.r = 1;
    s13.g = 1;
    s13.b = 1;
    s13.a = 1;
    c20.color = s13;
    c20.blending = 0;
    world.setComponentData(e3, c20);
    var c21 = new ut.Core2D.TransformNode();
    c21.parent = e1;
    world.setComponentData(e4, c21);
    var c22 = new ut.Core2D.TransformLocalPosition();
    var s14 = new ut.Math.Vector3();
    s14.x = -48.68;
    s14.y = 1.66;
    s14.z = 0;
    c22.position = s14;
    world.setComponentData(e4, c22);
    var c23 = new ut.Core2D.TransformLocalRotation();
    var s15 = new ut.Math.Quaternion();
    s15.x = 0;
    s15.y = 0;
    s15.z = 0;
    s15.w = 1;
    c23.rotation = s15;
    world.setComponentData(e4, c23);
    var c24 = new ut.Core2D.TransformLocalScale();
    var s16 = new ut.Math.Vector3();
    s16.x = 1;
    s16.y = 1;
    s16.z = 1;
    c24.scale = s16;
    world.setComponentData(e4, c24);
    var c25 = new ut.Core2D.Sprite2DRenderer();
    c25.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/bg5');
    var s17 = new ut.Core2D.Color();
    s17.r = 1;
    s17.g = 1;
    s17.b = 1;
    s17.a = 1;
    c25.color = s17;
    c25.blending = 0;
    world.setComponentData(e4, c25);
    var c26 = new ut.Core2D.TransformNode();
    c26.parent = e1;
    world.setComponentData(e5, c26);
    var c27 = new ut.Core2D.TransformLocalPosition();
    var s18 = new ut.Math.Vector3();
    s18.x = -89.816;
    s18.y = 1.66;
    s18.z = 0;
    c27.position = s18;
    world.setComponentData(e5, c27);
    var c28 = new ut.Core2D.TransformLocalRotation();
    var s19 = new ut.Math.Quaternion();
    s19.x = 0;
    s19.y = 0;
    s19.z = 0;
    s19.w = 1;
    c28.rotation = s19;
    world.setComponentData(e5, c28);
    var c29 = new ut.Core2D.TransformLocalScale();
    var s20 = new ut.Math.Vector3();
    s20.x = 1;
    s20.y = 1;
    s20.z = 1;
    c29.scale = s20;
    world.setComponentData(e5, c29);
    var c30 = new ut.Core2D.Sprite2DRenderer();
    c30.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/bg4');
    var s21 = new ut.Core2D.Color();
    s21.r = 1;
    s21.g = 1;
    s21.b = 1;
    s21.a = 1;
    c30.color = s21;
    c30.blending = 0;
    world.setComponentData(e5, c30);
    var c31 = new ut.Core2D.TransformNode();
    c31.parent = e1;
    world.setComponentData(e6, c31);
    var c32 = new ut.Core2D.TransformLocalPosition();
    var s22 = new ut.Math.Vector3();
    s22.x = -145.7;
    s22.y = 1.7;
    s22.z = 0;
    c32.position = s22;
    world.setComponentData(e6, c32);
    var c33 = new ut.Core2D.TransformLocalRotation();
    var s23 = new ut.Math.Quaternion();
    s23.x = 0;
    s23.y = 0;
    s23.z = 0;
    s23.w = 1;
    c33.rotation = s23;
    world.setComponentData(e6, c33);
    var c34 = new ut.Core2D.TransformLocalScale();
    var s24 = new ut.Math.Vector3();
    s24.x = 1;
    s24.y = 1;
    s24.z = 1;
    c34.scale = s24;
    world.setComponentData(e6, c34);
    var c35 = new ut.Core2D.Sprite2DRenderer();
    c35.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/bg3');
    var s25 = new ut.Core2D.Color();
    s25.r = 1;
    s25.g = 1;
    s25.b = 1;
    s25.a = 1;
    c35.color = s25;
    c35.blending = 0;
    world.setComponentData(e6, c35);
    return [e0, e1, e2, e3, e4, e5, e6];
}

