/**
 * TINY GENERATED CODE, DO NOT EDIT BY HAND
 * @project HanaHana
 */

entities.game.MainGroup.name = "MainGroup";
entities.game.MainGroup.load = function(world) {
    var arch0 = world.createArchetype(game.Camera, game.Limits, game.Speed, game.TeleportLimit, this.Component, ut.Core2D.Camera2D, ut.Core2D.TransformLocalPosition, ut.Core2D.TransformLocalRotation, ut.Core2D.TransformLocalScale, ut.Core2D.TransformNode, ut.EditorExtensions.CameraCullingMask, ut.layers.Default)
    var e0 = world.createEntity(arch0);
    world.setEntityName(e0, "Camera");
    var arch1 = world.createArchetype(game.Background, this.Component, ut.Core2D.TransformNode, ut.layers.Default)
    var e1 = world.createEntity(arch1);
    world.setEntityName(e1, "Background");
    var arch2 = world.createArchetype(game.Background, this.Component, ut.Core2D.Sprite2DRenderer, ut.Core2D.TransformLocalPosition, ut.Core2D.TransformLocalRotation, ut.Core2D.TransformLocalScale, ut.Core2D.TransformNode, ut.layers.Default)
    var e2 = world.createEntity(arch2);
    world.setEntityName(e2, "Background");
    var e3 = world.createEntity(arch2);
    world.setEntityName(e3, "Background");
    var e4 = world.createEntity(arch2);
    world.setEntityName(e4, "Background");
    var c0 = new ut.Core2D.TransformNode();
    world.setComponentData(e0, c0);
    var c1 = new ut.Core2D.TransformLocalPosition();
    var s0 = new ut.Math.Vector3();
    s0.x = 17.4;
    s0.y = 0;
    s0.z = -1;
    c1.position = s0;
    world.setComponentData(e0, c1);
    var c2 = new ut.Core2D.TransformLocalRotation();
    var s1 = new ut.Math.Quaternion();
    s1.x = 0;
    s1.y = 0;
    s1.z = 0;
    s1.w = 1;
    c2.rotation = s1;
    world.setComponentData(e0, c2);
    var c3 = new ut.Core2D.TransformLocalScale();
    var s2 = new ut.Math.Vector3();
    s2.x = 1;
    s2.y = 1;
    s2.z = 1;
    c3.scale = s2;
    world.setComponentData(e0, c3);
    var c4 = new ut.Core2D.Camera2D();
    c4.halfVerticalSize = 5;
    var s3 = new ut.Math.Rect();
    s3.x = 0;
    s3.y = 0;
    s3.width = 1;
    s3.height = 1;
    c4.rect = s3;
    var s4 = new ut.Core2D.Color();
    s4.r = 0;
    s4.g = 0;
    s4.b = 0;
    s4.a = 1;
    c4.backgroundColor = s4;
    c4.clearFlags = 1;
    c4.cullingMask = [ut.layers.Default.cid, ut.layers.TransparentFX.cid, ut.layers.IgnoreRaycast.cid, ut.layers.Water.cid, ut.layers.UI.cid, ut.layers.Grid.cid, ut.layers.Cutscene.cid];
    c4.cullingMode = 2;
    world.setComponentData(e0, c4);
    var c5 = new game.Limits();
    c5.minY = -3;
    c5.maxY = 3;
    world.setComponentData(e0, c5);
    var c6 = new game.TeleportLimit();
    c6.maxX = 20;
    c6.minX = -20;
    world.setComponentData(e0, c6);
    var c7 = new game.Speed();
    c7.speed = 10;
    world.setComponentData(e0, c7);
    var c8 = new ut.EditorExtensions.CameraCullingMask();
    c8.mask = -1;
    world.setComponentData(e0, c8);
    var c9 = new ut.Core2D.TransformNode();
    world.setComponentData(e1, c9);
    var c10 = new ut.Core2D.TransformNode();
    c10.parent = e1;
    world.setComponentData(e2, c10);
    var c11 = new ut.Core2D.TransformLocalPosition();
    var s5 = new ut.Math.Vector3();
    s5.x = -21.601;
    s5.y = 0;
    s5.z = 0;
    c11.position = s5;
    world.setComponentData(e2, c11);
    var c12 = new ut.Core2D.TransformLocalRotation();
    var s6 = new ut.Math.Quaternion();
    s6.x = 0;
    s6.y = 0;
    s6.z = 0;
    s6.w = 1;
    c12.rotation = s6;
    world.setComponentData(e2, c12);
    var c13 = new ut.Core2D.TransformLocalScale();
    var s7 = new ut.Math.Vector3();
    s7.x = 1;
    s7.y = 1;
    s7.z = 1;
    c13.scale = s7;
    world.setComponentData(e2, c13);
    var c14 = new ut.Core2D.Sprite2DRenderer();
    c14.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/Background');
    var s8 = new ut.Core2D.Color();
    s8.r = 1;
    s8.g = 1;
    s8.b = 1;
    s8.a = 1;
    c14.color = s8;
    c14.blending = 0;
    world.setComponentData(e2, c14);
    var c15 = new ut.Core2D.TransformNode();
    c15.parent = e1;
    world.setComponentData(e3, c15);
    var c16 = new ut.Core2D.TransformLocalPosition();
    var s9 = new ut.Math.Vector3();
    s9.x = 21.5;
    s9.y = -1E-06;
    s9.z = 0;
    c16.position = s9;
    world.setComponentData(e3, c16);
    var c17 = new ut.Core2D.TransformLocalRotation();
    var s10 = new ut.Math.Quaternion();
    s10.x = 0;
    s10.y = 0;
    s10.z = 0;
    s10.w = 1;
    c17.rotation = s10;
    world.setComponentData(e3, c17);
    var c18 = new ut.Core2D.TransformLocalScale();
    var s11 = new ut.Math.Vector3();
    s11.x = 1;
    s11.y = 1;
    s11.z = 1;
    c18.scale = s11;
    world.setComponentData(e3, c18);
    var c19 = new ut.Core2D.Sprite2DRenderer();
    c19.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/Background');
    var s12 = new ut.Core2D.Color();
    s12.r = 1;
    s12.g = 1;
    s12.b = 1;
    s12.a = 1;
    c19.color = s12;
    c19.blending = 0;
    world.setComponentData(e3, c19);
    var c20 = new ut.Core2D.TransformNode();
    c20.parent = e1;
    world.setComponentData(e4, c20);
    var c21 = new ut.Core2D.TransformLocalPosition();
    var s13 = new ut.Math.Vector3();
    s13.x = 0;
    s13.y = 0;
    s13.z = 0;
    c21.position = s13;
    world.setComponentData(e4, c21);
    var c22 = new ut.Core2D.TransformLocalRotation();
    var s14 = new ut.Math.Quaternion();
    s14.x = 0;
    s14.y = 0;
    s14.z = 0;
    s14.w = 1;
    c22.rotation = s14;
    world.setComponentData(e4, c22);
    var c23 = new ut.Core2D.TransformLocalScale();
    var s15 = new ut.Math.Vector3();
    s15.x = 1;
    s15.y = 1;
    s15.z = 1;
    c23.scale = s15;
    world.setComponentData(e4, c23);
    var c24 = new ut.Core2D.Sprite2DRenderer();
    c24.sprite = ut.EntityLookupCache.getByName(world, 'assets/sprites/Background');
    var s16 = new ut.Core2D.Color();
    s16.r = 1;
    s16.g = 1;
    s16.b = 1;
    s16.a = 1;
    c24.color = s16;
    c24.blending = 0;
    world.setComponentData(e4, c24);
    return [e0, e1, e2, e3, e4];
}

